### ISSUE TITLE
Current Task List

### ISSUE THREAD

**Issue by MisterJames** [ClearMeasureLabs/ClearMeasureBootcamp#15]
This is the current order of items based on feasibility/priority for conversion of the project.

 - [x] #1 Convert Project to 2015 - everything should still "just work"
 - [x] #7 TeamCity CI Builds - see the green lights with current state of the repo
 - [x] #2 Update Projects to .NET 4.6 - now, retarget and get build passing
 - [x] #18 Multitarget the DLLs - export packages that can be used in mulitple frameworks
 - [x] #20 DB Initialization - account for new appbase path
 - [x] #19 Move to xUnit - update unit tests to new test framework and remove NUnit
 - [ ] #21 Move to xUnit - update integration tests
 - [x] #6 Tidy-Up - slim down any unneeded code before conversion
 - [ ] #3 Package Upgrades - refactoring as we go
 - [ ] #4 Language features - take advantage of the new bits in C#
 - [ ] Address versioning - should be independent of the build server/deployment stack

The next block of work will be (these need scoping):
 - #5 Moving to MVC 6 (an undertaking of it's own)
 - #9 Scriptable deployments/infrastructure as code

**Comment by jeffreypalermo** [comment]
Turning the chapter and cleaning up this issue.
